#######################################
# provide paths to your raw input data (fastq-s):
#######################################
input:
  tophat_strand_string: fr-firststrand
  raw_fastq_dir:
    D1:
      - /home/yiyuan/Desktop/D1/D1.sub.R1.fastq.gz
      - /home/yiyuan/Desktop/D1/D1.sub.R2.fastq.gz
    D2:
      - /home/yiyuan/Desktop/D1/D1.sub.R1.fastq.gz
      - /home/yiyuan/Desktop/D1/D1.sub.R2.fastq.gz

########################################
# sequence fasta files
########################################
fasta:
    transcript_file: "/home/yiyuan/Data/Ref/mm10/transcriptome/gencode.vM17.transcripts.top100.fa"
    genome_file: "/home/yiyuan/Data/Ref/mm10/genome/chr19.fa"

########################################
# annotation files
########################################
annotation:
    gtf_file: "/home/yiyuan/Data/Ref/mm10/gtf/gencode.vM17.chr_patch_hapl_scaff.annotation.gtf"
    gencode_boolean: true

########################################
# folder structure for reference
########################################
reference:
    base_dir: "/home/yiyuan/Data/Ref/mm10/"
    build_string: "mm10"
    salmon_dir: "salmon_ref"
    star_dir: "star_ref"
    star_sjdbOverhang_integer: 99
    tophat_bowtie2_dir: "bt2_ref"

# or on the cluster use scratch directory (for example, /hpc/users/liuy22/scratch)
intermediates:
    base_dir: "/home/yiyuan/Data/Pipeline/Inter"

output:
    base_dir: "/home/yiyuan/Data/Pipeline/Res/"
    fastqc_dir: 'fastqc'
    salmon_dir: "salmon_res"
    star_dir: "star_res"
    fastqc_dir: "fastqc_res"
    bamqc_dir: "bamqc_res"
    featurecounts_dir: "cnt_res"

########################################
# sambamba or samtools
########################################
tools:
    samtools_sambamba_string: "sambamba"
    sortIntervalByGivenChrOrder_perl_file: "/home/yiyuan/Downloads/picard/sortIntervalByGivenChrOrder.pl"

########################################
# computational steps
########################################
compute:
    run_fastqc_boolean: false
    run_star_index_boolean: false
    run_star_boolean: false
    run_bowtie2_index_boolean: false
    run_tophat_boolean: true
    run_salmon_index_boolean: false
    run_salmon_boolean: false
    run_bamqc_boolean: false
    run_featurecounts_boolean: false
